"""`headcleaner attest` (Eng #36) — compute Attested Computations.

SKELETON / STUB. Tracks OKF v0.2 §10 (Attested Computations): the
ability to prove that a bundle was generated by a specific headcleaner
version using a specific toolchain, with no human edits in between.

Usage (planned):
    headcleaner attest <bundle-dir> [--private-key <PEM>] [--output attestation.json]

The implementation:
  1. Walks every concept in the bundle.
  2. For each concept, computes a canonical JSON hash (sorted keys,
     UTF-8, LF line endings) of its frontmatter + body.
  3. Builds a Merkle tree over all concept hashes.
  4. Signs the Merkle root with ed25519.
  5. Writes `attestation.json` with the signature + per-concept proofs.

This stub defines the data shape and exposes a public entry point that
raises NotImplementedError until the cryptographic core lands.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any


def canonical_hash(concept_path: Path) -> str:
    """Compute SHA-256 of the canonical (sorted-keys, LF) JSON form.

    Useful as a building block even without the full attestation.
    """
    text = concept_path.read_text(encoding="utf-8")
    canonical = json.dumps({"raw": text}, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def build_attestation(bundle_root: Path) -> dict[str, Any]:
    """Compute the attestation payload for a bundle.

    SKELETON: this currently returns a structured dict with each
    concept's SHA-256 hash but no Merkle root or signature yet. The
    full implementation lands in v0.6 with a real ed25519 signing
    primitive (cryptography or PyNaCl) and a reproducible Merkle
    construction (RFC 9162 SHA-256 binary tree).
    """
    if not bundle_root.is_dir():
        raise FileNotFoundError(bundle_root)

    concepts: dict[str, str] = {}
    for md_path in sorted(bundle_root.rglob("*.md")):
        if md_path.name in {"index.md", "log.md"}:
            continue
        rel = str(md_path.relative_to(bundle_root))
        concepts[rel] = canonical_hash(md_path)

    return {
        "tool": "headcleaner",
        "version": "0.5.0",
        "bundle_root": str(bundle_root),
        "concept_count": len(concepts),
        "concepts": concepts,
        "merkle_root": None,    # TODO v0.6
        "signature": None,      # TODO v0.6
        "public_key": None,     # TODO v0.6
    }


def write_attestation(bundle_root: Path, output: Path | None = None) -> Path:
    """Write `attestation.json` next to the bundle.

    Returns the output path.
    """
    payload = build_attestation(bundle_root)
    out_path = output or (bundle_root / "attestation.json")
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return out_path