"""Post-conversion linter — reviews converted Markdown and OKF files.

Run after `headcleaner convert` to catch formatting issues before you
commit the bundle. Two kinds of checks:

  - **OKF structural**: required `type` key present, v0.2 trust family
    fields present, sources[] schema correct, file:// URIs valid, etc.
  - **Markdown body**: frontmatter delimiter pairs match, no orphaned
    code fences, line-length sanity, heading hierarchy.

Findings are emitted as colored lines (neon palette) and exit code is
1 if any `error`-level finding, 0 otherwise.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path

import yaml

from .theme import (
    NEON_CYAN,
    NEON_PINK,
    NEON_PURPLE,
    FG_MUTED,
    FG_TEXT,
    paint,
)


class Severity(str, Enum):
    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


@dataclass
class Finding:
    severity: Severity
    file: Path
    line: int | None
    rule: str
    message: str

    def format(self) -> str:
        sev_color = {
            Severity.ERROR: NEON_PINK,
            Severity.WARNING: NEON_PURPLE,
            Severity.INFO: NEON_CYAN,
        }[self.severity]
        sev_label = f"{self.severity.value:<7}"
        loc = f"{self.file.name}:{self.line}" if self.line else self.file.name
        return (
            "  "
            + paint(sev_label, sev_color, bold=True)
            + " "
            + paint(loc, FG_MUTED)
            + "  "
            + paint(f"[{self.rule}]", NEON_CYAN)
            + "  "
            + paint(self.message, FG_TEXT)
        )


# ---------------------------------------------------------------------------
# Rule helpers
# ---------------------------------------------------------------------------

_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _split_frontmatter(text: str) -> tuple[dict, str, int] | tuple[None, None, None]:
    """Return (frontmatter_dict, body_text, body_start_line)."""
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None, None, None
    try:
        fm = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return None, None, None
    body_start = m.end()
    body_start_line = text[:body_start].count("\n") + 1
    return fm, text[body_start:], body_start_line


# ---------------------------------------------------------------------------
# OKF rules
# ---------------------------------------------------------------------------

def check_okf(path: Path) -> list[Finding]:
    out: list[Finding] = []
    if path.name == "index.md":
        return out  # generated by us; skip

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        out.append(Finding(Severity.ERROR, path, None, "okf/io", f"cannot read: {e}"))
        return out

    fm, body, body_start = _split_frontmatter(text)
    if fm is None:
        out.append(Finding(Severity.ERROR, path, 1, "okf/frontmatter", "missing or invalid YAML frontmatter"))
        return out

    # OKF v0.2 §4.1: type is required
    if "type" not in fm or not isinstance(fm.get("type"), str) or not fm["type"]:
        out.append(Finding(Severity.ERROR, path, 2, "okf/type-required", "`type` is the only always-required OKF key; missing or empty"))
    elif len(fm["type"]) > 60:
        out.append(Finding(Severity.WARNING, path, 2, "okf/type-length", f"`type` is {len(fm['type'])} chars; OKF convention is short (<60)"))

    # resource: file:// URI when present
    resource = fm.get("resource")
    if resource is not None:
        if not isinstance(resource, str) or not resource.startswith("file://"):
            out.append(Finding(Severity.WARNING, path, 3, "okf/resource-uri", "`resource` should be a file:// URI"))

    # sources[] shape (OKF v0.2 §5.1)
    sources = fm.get("sources")
    if sources is not None:
        if not isinstance(sources, list) or not sources:
            out.append(Finding(Severity.ERROR, path, 5, "okf/sources-empty", "`sources` must be a non-empty list"))
        else:
            for i, src in enumerate(sources):
                if not isinstance(src, dict):
                    out.append(Finding(Severity.ERROR, path, 5, "okf/sources-shape", f"sources[{i}] must be a dict"))
                    continue
                if "uri" not in src:
                    out.append(Finding(Severity.WARNING, path, 5, "okf/sources-uri", f"sources[{i}] missing `uri`"))
                if "sha256" in src and not re.fullmatch(r"[0-9a-f]{64}", str(src["sha256"])):
                    out.append(Finding(Severity.ERROR, path, 5, "okf/sources-sha256", f"sources[{i}].sha256 is not a valid SHA-256 hex string"))

    # OKF v0.2 trust family
    if "status" not in fm:
        out.append(Finding(Severity.WARNING, path, 4, "okf/status-missing", "`status` not set; OKF v0.2 §5.2 recommends an explicit value"))
    if "verified" not in fm:
        out.append(Finding(Severity.WARNING, path, 4, "okf/verified-missing", "`verified` not set; OKF v0.2 §5.3 recommends an explicit actor tag"))

    # Body sanity
    if not body or not body.strip():
        out.append(Finding(Severity.ERROR, path, body_start, "okf/body-empty", "OKF concept has empty body"))

    return out


# ---------------------------------------------------------------------------
# Markdown rules
# ---------------------------------------------------------------------------

def check_markdown(path: Path) -> list[Finding]:
    out: list[Finding] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        out.append(Finding(Severity.ERROR, path, None, "md/io", f"cannot read: {e}"))
        return out

    fm, body, body_start = _split_frontmatter(text)
    if fm is None:
        out.append(Finding(Severity.WARNING, path, 1, "md/frontmatter-missing", "Markdown file has no frontmatter (consider adding OKF trust family)"))
        body = text  # lint body even without frontmatter
        body_start = 1

    # Orphaned code fences (odd count)
    fence_count = len(re.findall(r"(?m)^```", body))
    if fence_count % 2 != 0:
        out.append(Finding(Severity.ERROR, path, None, "md/code-fence-orphan", f"{fence_count} ``` fences found; odd count means an unclosed fence"))

    # Heading hierarchy: no skipped levels (h1 -> h3 etc.)
    last_level = 0
    for i, line in enumerate(body.splitlines(), start=body_start):
        m = re.match(r"^(#{1,6})\s", line)
        if m:
            level = len(m.group(1))
            if last_level and level > last_level + 1:
                out.append(Finding(Severity.WARNING, path, i, "md/heading-skip", f"heading jumps from h{last_level} to h{level}; readers expect linear hierarchy"))
            last_level = level

    # Long lines
    for i, line in enumerate(body.splitlines(), start=body_start):
        # naive visible-width check (ignores ANSI)
        if len(line) > 200:
            out.append(Finding(Severity.INFO, path, i, "md/line-length", f"line is {len(line)} chars (>200); consider wrapping"))

    return out


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

@dataclass
class Fix:
    """One safe auto-repair that the linter can apply."""
    file: Path
    new_text: str
    description: str


@dataclass
class LintSummary:
    scanned: int = 0
    errors: int = 0
    warnings: int = 0
    info: int = 0
    findings: list[Finding] = field(default_factory=list)
    fixes_applied: list[Fix] = field(default_factory=list)


def lint_directory(root: Path, *, okf_root: Path | None = None, md_root: Path | None = None) -> LintSummary:
    """Walk `root` (or specifically `okf_root` / `md_root`) and run all rules.

    Default behavior: walks the whole `root` and applies OKF rules to anything
    in an `okf/` subtree, MD rules to anything in a `_md/` subtree, and both
    to anything else.
    """
    summary = LintSummary()
    if not root.is_dir():
        return summary

    for md_path in sorted(root.rglob("*.md")):
        rel = md_path.relative_to(root)
        rel_str = str(rel)
        summary.scanned += 1

        if "okf" in rel.parts:
            findings = check_okf(md_path)
        elif "_md" in rel.parts:
            findings = check_markdown(md_path)
        else:
            findings = check_okf(md_path) + check_markdown(md_path)

        for f in findings:
            summary.findings.append(f)
            if f.severity == Severity.ERROR:
                summary.errors += 1
            elif f.severity == Severity.WARNING:
                summary.warnings += 1
            else:
                summary.info += 1

    return summary


def main(args: list[str] | None = None) -> int:
    """CLI entry point for `headcleaner-lint`."""
    import argparse

    parser = argparse.ArgumentParser(
        prog="headcleaner-lint",
        description="Review converted Markdown / OKF for formatting issues.",
    )
    parser.add_argument("directory", type=Path, help="Output directory to lint")
    parser.add_argument("--strict", action="store_true", help="Treat warnings as errors")
    parser.add_argument("--no-color", action="store_true", help="Disable ANSI colors")
    parser.add_argument(
        "--fix",
        action="store_true",
        help="Auto-repair safe issues to <directory>.fixed/ (never overwrites source)",
    )
    parser.add_argument(
        "--fix-out",
        type=Path,
        default=None,
        help="Override the --fix output directory (default: <directory>.fixed)",
    )
    args = parser.parse_args(args)

    summary = lint_directory(args.directory)

    if not summary.findings:
        print(paint(f"  ✓ {summary.scanned} files clean", NEON_CYAN, bold=True))
        return 0

    for f in summary.findings:
        print(f.format())

    print()
    print(
        paint(f"  scanned: {summary.scanned}", FG_MUTED)
        + paint(f"   errors: {summary.errors}", NEON_PINK, bold=True)
        + paint(f"   warnings: {summary.warnings}", NEON_PURPLE)
        + paint(f"   info: {summary.info}", NEON_CYAN)
    )

    if summary.errors:
        return 1
    if args.strict and summary.warnings:
        return 1

    # --fix: compute and apply safe auto-repairs
    if args.fix:
        out_root = args.fix_out or args.directory.with_name(args.directory.name + ".fixed")
        seen: set[Path] = set()
        fixes: list[Fix] = []
        for f in summary.findings:
            if f.file in seen:
                continue
            seen.add(f.file)
            fix = build_fix(f.file)
            if fix is not None:
                fixes.append(fix)
        applied = apply_fixes(fixes, out_root)
        for fix in applied:
            print(
                "  "
                + paint("fixed", NEON_CYAN, bold=True)
                + " "
                + paint(fix.file.name, FG_MUTED)
                + "  "
                + paint(fix.description, NEON_PURPLE)
            )
        if applied:
            print()
            print(
                paint(f"  ✓ {len(applied)} fix(es) applied to {out_root}", NEON_CYAN, bold=True)
            )
        else:
            print(paint("  · no safe fixes available", FG_MUTED))

    return 0


# ---------------------------------------------------------------------------
# Auto-repair (--fix)
# ---------------------------------------------------------------------------

def build_fix(path: Path) -> Fix | None:
    """Compute a single safe auto-repair for the given file.

    Returns None if no repair is possible (or would be unsafe).
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None

    if path.name == "index.md":
        return None  # never auto-edit generated index files

    fm, body, _ = _split_frontmatter(text)
    if fm is None:
        return None  # no frontmatter → not an OKF concept → don't auto-touch

    # Determine the trust family additions
    additions: dict = {}
    if not fm.get("type"):
        return None  # can't infer a sensible 'type' — leave for human
    if not fm.get("status"):
        additions["status"] = "unverified"
    if not fm.get("verified"):
        additions["verified"] = "human:pending"
    if not fm.get("stale_after"):
        # OKF §5.2 freshness: 180 days from now
        from datetime import datetime, timezone, timedelta
        additions["stale_after"] = (datetime.now(timezone.utc) + timedelta(days=180)).strftime("%Y-%m-%d")
    if not fm.get("sources"):
        # Don't invent sources; that's dishonest. Skip.
        return None
    if not fm.get("resource"):
        # Derive resource from sources[0].uri when both exist (both are
        # file paths the producer already attested to).
        sources = fm.get("sources") or []
        if isinstance(sources, list) and sources and isinstance(sources[0], dict) and sources[0].get("uri"):
            additions["resource"] = sources[0]["uri"]
        # else: skip — can't safely invent the resource URI

    if not additions:
        return None  # nothing to fix

    fm.update(additions)
    yaml_block = yaml.safe_dump(fm, sort_keys=False, allow_unicode=True).strip()
    new_text = f"---\n{yaml_block}\n---\n\n{body.lstrip()}"

    desc = "; ".join(f"+{k}" for k in additions)
    return Fix(file=path, new_text=new_text, description=f"added {desc}")


def apply_fixes(fixes: list[Fix], out_root: Path) -> list[Fix]:
    """Write fixes to `<out_root>/<file-relative-path>`; return the fixes actually applied."""
    applied: list[Fix] = []
    out_root.mkdir(parents=True, exist_ok=True)
    for fix in fixes:
        try:
            target = out_root / fix.file.name
            target.write_text(fix.new_text, encoding="utf-8")
            applied.append(fix)
        except OSError:
            continue
    return applied


if __name__ == "__main__":
    raise SystemExit(main())
